# Python 3 w/ grpcio and grpcio-tools added for faster buils
FROM arm32v7/python:3.6-slim-buster

RUN ln -sf python3 /usr/bin/python

RUN python -m venv /app/env
ENV PATH="/app/env/bin:$PATH"

RUN pip install --upgrade pip
RUN python3 -m pip install --upgrade setuptools
RUN pip install grpcio && pip install grpcio-tools
